
#ifndef PROCESSOR_INTEL_PENTIUMII
#define PROCESSOR_INTEL_PENTIUMII 686
#endif

#ifndef PROCESSOR_ARM_7TDMI
#define PROCESSOR_ARM_7TDMI     70001
#endif

#ifndef PROCESSOR_ARM11
#define PROCESSOR_ARM11         4352
#endif

#ifndef PROCESSOR_ARM11MP
#define PROCESSOR_ARM11MP       4353
#endif

#ifndef PROCESSOR_ARM_CORTEX
#define PROCESSOR_ARM_CORTEX    43775
#endif

#ifndef PROCESSOR_HITACHI_SH3E
#define PROCESSOR_HITACHI_SH3E  10004
#endif

#ifndef PROCESSOR_HITACHI_SH4
#define PROCESSOR_HITACHI_SH4	10005
#endif

#ifndef PROCESSOR_MIPS_R2000
#define PROCESSOR_MIPS_R2000    2000
#endif

#ifndef PROCESSOR_MIPS_R3000
#define PROCESSOR_MIPS_R3000    3000
#endif

#ifndef PROCESSOR_MIPS_R5000
#define PROCESSOR_MIPS_R5000    5000
#endif

#ifndef PROCESSOR_SHx_SH3DSP
#define PROCESSOR_SHx_SH3DSP    105
#endif

#ifndef PROCESSOR_PPC_403
#define PROCESSOR_PPC_403       403
#endif

#ifndef PROCESSOR_MOTOROLA_821
#define PROCESSOR_MOTOROLA_821  821
#endif

#ifndef PROCESSOR_CEF
#define PROCESSOR_CEF           0x494f
#endif

#ifndef PROCESSOR_ARCHITECTURE_SHX
#define PROCESSOR_ARCHITECTURE_SHX   4
#endif
