//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ResInfo.rc
//
#define IDI_RESINFO                     101
#define IDI_RESINFO1                    102
#define IDI_RESINFO2                    103
#define IDI_RESINFO3                    104
#define IDI_RESINFO4                    105
#define IDI_RESINFO5                    106
#define IDI_RESINFO6                    107
#define IDI_RESINFO7                    108
#define IDI_RESINFO8                    109
#define IDD_GER_RESINFO1                110
#define IDD_GER_RESINFO2                111
#define IDD_GER_RESINFO3                112
#define IDD_GER_RESINFO4                113
#define IDD_GER_RESINFO5                114
#define IDD_GER_RESINFO6                115
#define IDD_GER_RESINFO7                116
#define IDD_GER_RESINFO8                117
#define IDD_ENG_RESINFO1                118
#define IDD_ENG_RESINFO2                119
#define IDD_ENG_RESINFO3                120
#define IDD_ENG_RESINFO4                121
#define IDD_ENG_RESINFO5                122
#define IDD_ENG_RESINFO6                123
#define IDD_ENG_RESINFO7                124
#define IDD_ENG_RESINFO8                125
#define IDR_ACCELERATOR                 126
#define IDR_GER_MENU                    127
#define IDR_ENG_MENU                    128
#define IDI_BAT000C                     200
#define IDI_BAT010C                     201
#define IDI_BAT020C                     202
#define IDI_BAT030C                     203
#define IDI_BAT040C                     204
#define IDI_BAT050C                     205
#define IDI_BAT060C                     206
#define IDI_BAT070C                     207
#define IDI_BAT080C                     208
#define IDI_BAT090C                     209
#define IDI_BAT100C                     210
#define IDI_BATUNKNC                    211
#define IDI_BATLOADC                    212
#define IDI_BATNONEC                    213
#define IDI_MEM000C                     250
#define IDI_MEM010C                     251
#define IDI_MEM020C                     252
#define IDI_MEM030C                     253
#define IDI_MEM040C                     254
#define IDI_MEM050C                     255
#define IDI_MEM060C                     256
#define IDI_MEM070C                     257
#define IDI_MEM080C                     258
#define IDI_MEM090C                     259
#define IDI_MEM100C                     260
#define IDI_MEMUNKNC                    261
#define IDI_BAT000B                     300
#define IDI_BAT010B                     301
#define IDI_BAT020B                     302
#define IDI_BAT030B                     303
#define IDI_BAT040B                     304
#define IDI_BAT050B                     305
#define IDI_BAT060B                     306
#define IDI_BAT070B                     307
#define IDI_BAT080B                     308
#define IDI_BAT090B                     309
#define IDI_BAT100B                     310
#define IDI_BATUNKNB                    311
#define IDI_BATLOADB                    312
#define IDI_BATNONEB                    313
#define IDI_MEM000B                     350
#define IDI_MEM010B                     351
#define IDI_MEM020B                     352
#define IDI_MEM030B                     353
#define IDI_MEM040B                     354
#define IDI_MEM050B                     355
#define IDI_MEM060B                     356
#define IDI_MEM070B                     357
#define IDI_MEM080B                     358
#define IDI_MEM090B                     359
#define IDI_MEM100B                     360
#define IDI_MEMUNKNB                    361
#define IDI_CPU000C                     370
#define IDI_CPU001C                     371
#define IDI_CPU002C                     372
#define IDI_CPU003C                     373
#define IDI_CPU004C                     374
#define IDI_CPU005C                     375
#define IDI_CPU006C                     376
#define IDI_CPU007C                     377
#define IDI_CPU008C                     378
#define IDI_CPU009C                     379
#define IDI_CPU010C                     380
#define IDI_CPU011C                     381
#define IDI_CPUUNKNC                    382
#define IDI_CPU000B                     385
#define IDI_CPU001B                     386
#define IDI_CPU002B                     387
#define IDI_CPU003B                     388
#define IDI_CPU004B                     389
#define IDI_CPU005B                     390
#define IDI_CPU006B                     391
#define IDI_CPU007B                     392
#define IDI_CPU008B                     393
#define IDI_CPU009B                     394
#define IDI_CPU010B                     395
#define IDI_CPU011B                     396
#define IDI_CPUUNKNB                    397
#define IDS_GER_BAT_MAIN_BACKUP         401
#define IDS_GER_BAT_MAIN                402
#define IDS_GER_BAT_BACKUP              403
#define IDS_GER_BAT_AC                  404
#define IDS_GER_FLAG_HIGH               405
#define IDS_GER_FLAG_LOW                406
#define IDS_GER_FLAG_CRITICAL           407
#define IDS_GER_FLAG_CHARGING           408
#define IDS_GER_FLAG_NO_BATTERY         409
#define IDS_GER_AC_OFFLINE              410
#define IDS_GER_AC_ONLINE               411
#define IDS_GER_AC_BACKUP               412
#define IDS_GER_STORAGECARD             413
#define IDS_GER_FILLED                  414
#define IDS_GER_FREE                    415
#define IDS_GER_UNKNOWN                 416
#define IDS_GER_PROCESSES               417
#define IDS_GER_THREADS                 418
#define IDS_GER_WINDOWS                 419
#define IDS_GER_PIXELS                  420
#define IDS_GER_COLORS                  421
#define IDS_GER_GRAYSCALE               422
#define IDS_GER_ELECTRIC                423
#define IDS_GER_FILES                   424
#define IDS_GER_DBASE                   425
#define IDS_GER_PCMCIA                  426
#define IDS_GER_BTN_PROC                427
#define IDS_GER_BTN_WND                 428
#define IDS_GER_RESET                   429
#define IDS_GER_BTN_PAUSE               430
#define IDS_GER_BTN_RESUME              431
#define IDS_GER_HIDE                    432
#define IDS_GER_EXIT                    433
#define IDP_GER_BATTERY                 434
#define IDP_GER_RESET                   435
#define IDP_GER_PROCESS                 436
#define IDP_GER_ACCESS                  437
#define IDP_GER_SYSTASK                 438
#define IDP_GER_TERMINATE               439
#define IDP_GER_NETWORK                 440
#define IDP_GER_REBOOT                  441
#define IDP_GER_FAILBOOT                442
#define IDP_GER_NOTFOUND                443
#define IDP_GER_NOPCCARD                444
#define IDS_GER_TOOLHELP                445
#define IDS_GER_SNAPSHOT                446
#define IDS_GER_MEMORY                  447
#define IDS_GER_MAXTASKS                448
#define IDS_ENG_BAT_MAIN_BACKUP         801
#define IDS_ENG_BAT_MAIN                802
#define IDS_ENG_BAT_BACKUP              803
#define IDS_ENG_BAT_AC                  804
#define IDS_ENG_FLAG_HIGH               805
#define IDS_ENG_FLAG_LOW                806
#define IDS_ENG_FLAG_CRITICAL           807
#define IDS_ENG_FLAG_CHARGING           808
#define IDS_ENG_FLAG_NO_BATTERY         809
#define IDS_ENG_AC_OFFLINE              810
#define IDS_ENG_AC_ONLINE               811
#define IDS_ENG_AC_BACKUP               812
#define IDS_ENG_STORAGECARD             813
#define IDS_ENG_FILLED                  814
#define IDS_ENG_FREE                    815
#define IDS_ENG_UNKNOWN                 816
#define IDS_ENG_PROCESSES               817
#define IDS_ENG_THREADS                 818
#define IDS_ENG_WINDOWS                 819
#define IDS_ENG_PIXELS                  820
#define IDS_ENG_COLORS                  821
#define IDS_ENG_GRAYSCALE               822
#define IDS_ENG_ELECTRIC                823
#define IDS_ENG_FILES                   824
#define IDS_ENG_DBASE                   825
#define IDS_ENG_PCMCIA                  826
#define IDS_ENG_BTN_PROC                827
#define IDS_ENG_BTN_WND                 828
#define IDS_ENG_RESET                   829
#define IDS_ENG_BTN_PAUSE               830
#define IDS_ENG_BTN_RESUME              831
#define IDS_ENG_HIDE                    832
#define IDS_ENG_EXIT                    833
#define IDP_ENG_BATTERY                 834
#define IDP_ENG_RESET                   835
#define IDP_ENG_PROCESS                 836
#define IDP_ENG_ACCESS                  837
#define IDP_ENG_SYSTASK                 838
#define IDP_ENG_TERMINATE               839
#define IDP_ENG_NETWORK                 840
#define IDP_ENG_REBOOT                  841
#define IDP_ENG_FAILBOOT                842
#define IDP_ENG_NOTFOUND                843
#define IDP_ENG_NOPCCARD                844
#define IDS_ENG_TOOLHELP                845
#define IDS_ENG_SNAPSHOT                846
#define IDS_ENG_MEMORY                  847
#define IDS_ENG_MAXTASKS                848
#define IDC_HIDE                        1001
#define IDC_ADV_BAT                     1002
#define IDC_RESET                       1003
#define IDC_BAT                         1004
#define IDC_PROGRESS_BAT                1005
#define IDC_BAT_STATUS                  1006
#define IDC_TEXT_WORKING                1007
#define IDC_TIME_WORKING                1008
#define IDC_TEXT_SUSPEND                1009
#define IDC_TIME_SUSPEND                1010
#define IDC_DATABASE                    1011
#define IDC_SEARCH                      1012
#define IDC_MEM                         1013
#define IDC_PROGRESS_MEM                1014
#define IDC_FILLED_MEM                  1015
#define IDC_FREE_MEM                    1016
#define IDC_OBJ                         1017
#define IDC_PROGRESS_OBJ                1018
#define IDC_FILLED_OBJ                  1019
#define IDC_FREE_OBJ                    1020
#define IDC_NEXT                        1021
#define IDC_PC_CARDS                    1022
#define IDC_DIR_CARD1                   1023
#define IDC_PERCENT_CARD1               1024
#define IDC_PROGRESS_CARD1              1025
#define IDC_FILLED_CARD1                1026
#define IDC_FREE_CARD1                  1027
#define IDC_DIR_CARD2                   1028
#define IDC_PERCENT_CARD2               1029
#define IDC_PROGRESS_CARD2              1030
#define IDC_FILLED_CARD2                1031
#define IDC_FREE_CARD2                  1032
#define IDC_TASKLIST                    1033
#define IDC_TASKINFO                    1034
#define IDC_TASKS                       1035
#define IDC_END_TASK                    1036
#define IDC_NETWORK                     1037
#define IDC_REBOOT                      1038
#define IDC_OEMINFO                     1039
#define IDC_PLATFORM                    1040
#define IDC_OSVERSION                   1041
#define IDC_MEMORY                      1042
#define IDC_PROCESSOR                   1043
#define IDC_DISPLAY                     1044
#define IDC_APPLY                       1045
#define IDC_COLOR                       1046
#define IDC_OPT_RESET                   1047
#define IDC_OPT_BATICON                 1048
#define IDC_OPT_MEMICON                 1049
#define IDC_OPT_CPUICON                 1050
#define IDC_OPT_STATICON                1051
#define IDC_OPT_COLOR                   1052
#define IDC_HOMEPAGE                    1053
#define IDC_APPNAME                     1054
#define IDC_VERSION                     1055
#define IDC_RELEASE                     1056
#define IDC_COPYRIGHT                   1057
#define IDC_AUTHOR                      1058
#define IDC_URL                         1059
#define IDC_FAQ                         1060
#define IDC_HISTORY                     1061
#define IDC_SPEED                       1062
#define IDC_PAUSE                       1063
#define IDC_ACCEPT                      1064

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
